# Generated by Django 5.2 on 2025-04-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=255)),
                ('mukdary', models.PositiveIntegerField()),
                ('birlik_baha', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ulanyjy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('adres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProyektEnjam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mukdary', models.PositiveIntegerField(default=1)),
                ('enjam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taslama.enjam')),
            ],
        ),
        migrations.CreateModel(
            name='Taslama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=255)),
                ('gornusi', models.CharField(choices=[('uly', 'Uly Taslama'), ('orta', 'Orta Taslama'), ('kici', 'Kiçi Taslama')], max_length=10)),
                ('baslanan_senesi', models.DateField()),
                ('tamamlanjak_senesi', models.DateField()),
                ('status', models.CharField(choices=[('planlanan', 'Meýilleşdirilen'), ('dowam', 'Dowam edýär'), ('tamam', 'Tamamlandy')], max_length=20)),
                ('bellik', models.TextField(blank=True)),
                ('enjamlary', models.ManyToManyField(related_name='proyektler', through='taslama.ProyektEnjam', to='taslama.enjam')),
                ('müşderi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taslama.ulanyjy')),
            ],
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surat', models.ImageField(upload_to='media/')),
                ('bellik', models.CharField(blank=True, max_length=255)),
                ('proyekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suratlar', to='taslama.taslama')),
            ],
        ),
        migrations.AddField(
            model_name='proyektenjam',
            name='proyekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taslama.taslama'),
        ),
        migrations.CreateModel(
            name='Is_Hasabatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=255)),
                ('tamamlandy', models.BooleanField(default=False)),
                ('bellik', models.TextField(blank=True, null=True)),
                ('baslanys_wagty', models.DateTimeField(blank=True, null=True)),
                ('gutarany_wagty', models.DateTimeField(blank=True, null=True)),
                ('proyekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isler', to='taslama.taslama')),
            ],
        ),
    ]
