# Generated by Django 5.2 on 2025-04-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taslama', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enjam',
            options={'verbose_name': 'Enjam', 'verbose_name_plural': 'Enjamlar'},
        ),
        migrations.AlterModelOptions(
            name='is_hasabatlar',
            options={'verbose_name': 'Is Hasabat', 'verbose_name_plural': 'Is Hasabatlar'},
        ),
        migrations.AlterModelOptions(
            name='proyektenjam',
            options={'verbose_name': 'Proyekt Enjam', 'verbose_name_plural': 'Proyekt Enjamlary'},
        ),
        migrations.AlterModelOptions(
            name='surat',
            options={'verbose_name': 'Surat', 'verbose_name_plural': 'Suratlar'},
        ),
        migrations.AlterModelOptions(
            name='taslama',
            options={'verbose_name': 'Taslama', 'verbose_name_plural': 'Taslamalar'},
        ),
        migrations.AlterModelOptions(
            name='ulanyjy',
            options={'verbose_name': 'Ulanyjy', 'verbose_name_plural': 'Ulanyjylar'},
        ),
        migrations.RemoveField(
            model_name='enjam',
            name='birlik_baha',
        ),
        migrations.AddField(
            model_name='enjam',
            name='bahasy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enjam',
            name='suraty',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
