# Generated by Django 5.2 on 2025-04-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taslama', '0002_alter_enjam_options_alter_is_hasabatlar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taslama',
            name='müşderi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taslama.ulanyjy'),
        ),
    ]
