# Generated by Django 5.2 on 2025-04-05 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taslama', '0003_alter_taslama_müşderi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surat',
            name='proyekt',
        ),
        migrations.AddField(
            model_name='surat',
            name='ady',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taslama',
            name='suraty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taslama.surat'),
        ),
    ]
