# Generated by Django 5.2 on 2025-04-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taslama', '0004_remove_surat_proyekt_surat_ady_taslama_suraty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taslama',
            name='bellik',
        ),
        migrations.AddField(
            model_name='taslama',
            name='beyan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
